name: Build Image & Publish Package

on:
  push:
    tags:
      - '*'

jobs:
  build-docker-and-package:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Installing dependencies
        run: |
          sudo apt update && sudo apt install make -y
          echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_HUB_LOGIN }}" --password-stdin
          sudo apt update && sudo apt install make python3-pip python3-setuptools -y
          pip3 install twine
      - name: install buildx
        id: buildx
        uses: crazy-max/ghaction-docker-buildx@v1
      - name: Build package
        run: make install
      - name: Publish package
        run: python3 -m twine upload dist/* -u "${{ secrets.PYPI_USERNAME }}" -p "${{ secrets.PYPI_PASSWORD }}"
      - name: Build image
        run: make build-docker
      - name: Publish image
        run: make publish-docker
